### ISSUE TITLE
since version 0.06 this requires posix' tzset, which breaks tests on windows and has huge toolchain effects via Plack

### ISSUE THREAD

**Issue by wchristian** [cho45/Test-Time#10]
From 0.05 to 0.06 tzset was added to basic.t, but windows does not have that function:

    t/01_base.t ..... 2/? POSIX::tzset not implemented on this architecture at t/01_base.t line 16.
    # Tests were run but no plan was declared and done_testing() was not seen.

Since Plack depends on the module via Cookie::Baker, this means on windows right now, installing most web frameworks is broken due to the above error.

**Comment by plicease** [comment]
Another non-ideal, but okay workaround is to use `_tzset` from `Time::Piece` on MSWin32.  This is what I did when I had a similar problem in `String::Template`.

https://metacpan.org/source/PLICEASE/String-Template-0.21/t/string_template__tz.t#L13

**Comment by sdondley** [comment]
Confirming. Same problem on a Windows 8 machine. Had to do `cpanm --force Test::Time` to get Plack installed.

**Comment by cho45** [comment]
Fixed on #13 and released as 0.08.
